spring:
  application:
    name: organization-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/license-dev
    username: root
    password: root
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 0


eureka:
  instance:
    # Адрес регистрационного центра
    hostname: localhost
  client:
    # url куда будет происходиться регистрация микросервисов
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8070/eureka/


logging:
  # Формат вывода логов
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n"
